In [1]:
import numpy as np

array_x = np.array([100.12, 120.23, 130.91])


In [3]:
print(array_x.dtype)

float64


In [39]:
np.sctypes

{'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'others': [bool, object, bytes, str, numpy.void],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]}

In [4]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [5]:
np.int64.mro()

[numpy.int64,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [55]:
np.unicode_.mro()

[numpy.str_, str, numpy.character, numpy.flexible, numpy.generic, object]

In [15]:
np.float64(100.12).nbytes

8

In [35]:
np.str_('n').nbytes

4

In [36]:
np.str_('numpy').nbytes

20

In [42]:
np.str_('').nbytes

20

In [16]:
np.float64(array_x).nbytes

24

In [22]:
array_x2 = array_x.astype(np.float32)

In [24]:
array_x2

array([100.12, 120.23, 130.91], dtype=float32)

In [25]:
np.float32(array_x2).nbytes

12

In [2]:
array_x.__array_interface__

{'data': (140547047960768, False),
 'descr': [('', '<f8')],
 'shape': (3,),
 'strides': None,
 'typestr': '<f8',
 'version': 3}

In [43]:
import numpy as np
X = np.array([1,2,3,2,1,3,9,8,11,12,10,11,14,25,26,24,30,22,24,27])

X[::4]

array([ 1,  1, 11, 14, 30])

In [46]:
nd_1 = np.random.randn(4, 6, 8)

In [47]:
nd_1

array([[[ 0.64900179, -0.00494884, -0.97565618, -0.78851039],
        [ 0.05165607,  0.068948  ,  1.54542042,  1.68553396],
        [-0.80311258,  0.95298682, -0.85879725,  0.67537715]],

       [[ 0.24014811, -0.41894241, -0.00855571,  0.43483418],
        [ 0.43001636, -0.75432657,  1.16955535, -0.42471807],
        [ 0.6781286 , -1.87876591,  1.02969921,  0.43215107]]])

In [57]:
nd_2 = nd_1[::, ::2, ::2]

In [59]:
print(nd_2)

[[[ 0.64900179 -0.97565618]
  [-0.80311258 -0.85879725]]

 [[ 0.24014811 -0.00855571]
  [ 0.6781286   1.02969921]]]


In [61]:
nd_1.__array_interface__

{'data': (140547049888960, False),
 'descr': [('', '<f8')],
 'shape': (2, 3, 4),
 'strides': None,
 'typestr': '<f8',
 'version': 3}

In [60]:
nd_2.__array_interface__

{'data': (140547049888960, False),
 'descr': [('', '<f8')],
 'shape': (2, 2, 2),
 'strides': (96, 64, 16),
 'typestr': '<f8',
 'version': 3}

In [2]:
nd_1 = np.random.randn(400, 600)

In [3]:
nd_2 = np.random.randn(400, 600*20)[::, ::20]

In [4]:
print(nd_1.shape, nd_2.shape)

(400, 600) (400, 600)


In [10]:
%%timeit
np.cumprod(nd_1)

802 µs ± 20.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
%%timeit
np.cumprod(nd_2)

2.12 ms ± 71.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
nd_1.__array_interface__

{'data': (4569473024, False),
 'descr': [('', '<f8')],
 'shape': (400, 600),
 'strides': None,
 'typestr': '<f8',
 'version': 3}

In [13]:
nd_2.__array_interface__

{'data': (4603252736, False),
 'descr': [('', '<f8')],
 'shape': (400, 600),
 'strides': (96000, 160),
 'typestr': '<f8',
 'version': 3}

In [14]:
import numexpr as ne

In [16]:
%%timeit
2 * nd_2 + 48

1.4 ms ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%%timeit
ne.evaluate("2 * nd_2 + 48")

843 µs ± 8.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
array_x[:2].__array_interface__['data'][0]

140268017895888

In [3]:
array_x[:2].__array_interface__['data'][0] == array_x.__array_interface__['data'][0]

True

In [4]:
array_x[1:].__array_interface__['data'][0]

140268017895896

In [5]:
array_x[1:].__array_interface__['data'][0] == array_x.__array_interface__['data'][0]

False

In [21]:
array_f = np.array([[100.12, 120.23, 130.91], [90.45, 110.32, 120.32]])
print(array_f)

[[100.12 120.23 130.91]
 [ 90.45 110.32 120.32]]


In [22]:
array_f.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [30]:
array_x.flags['C_CONTIGUOUS']

True

In [32]:
array_x.flags.c_contiguous

True

In [26]:
np.reshape(array_f, (3, 2), order='C')

array([[100.12, 120.23],
       [130.91,  90.45],
       [110.32, 120.32]])

In [27]:
np.reshape(array_f, (3, 2), order='F')

array([[100.12, 110.32],
       [ 90.45, 130.91],
       [120.23, 120.32]])

In [24]:
shape = (400,400,400)
array_x = np.random.random_sample(shape)

In [18]:
import cProfile
import re

cProfile.run('array_x *= 2')

         3 function calls in 0.065 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.065    0.065    0.065    0.065 <string>:1(<module>)
        1    0.000    0.000    0.065    0.065 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [20]:
import cProfile
import re

cProfile.run('array_y = array_x * 2')

         3 function calls in 0.318 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.318    0.318    0.318    0.318 <string>:1(<module>)
        1    0.000    0.000    0.318    0.318 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [84]:
shape_x = (8000,3000)
array_x = np.random.random_sample(shape_x)

In [85]:
%%timeit
np.cumprod(array_x)

176 ms ± 2.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [86]:
# Output array should have same type and dimensions with expected output of the operations
output_array = np.zeros(array_x.shape[0] * array_x.shape[1])

In [87]:
%%timeit
np.cumprod(array_x, out=output_array)

86.4 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [99]:
np.__config__.show()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


In [3]:
!pip install vprof

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
