## Performance Benchmarks

### Timer function

In [270]:
import inspect
import time
from datetime import datetime

def timer(*args, operation, n):
    """
    Returns average time spent 
    for given operation and arguments.
    
    Parameters
    ----------
        *args: list (of numpy.ndarray, numpy.matrixlib.defmatrix.matrix or both)
            one or more numpy vectors or matrices
        operation: function
            numpy or scipy operation to be applied to given arguments
        n: int 
            number of iterations to apply given operation

    Returns
    -------
        avg_time_spent: double
            Average time spent to apply given operation
        std_time_spent: double
            Standard deviation of time spent to apply given operation
        
    Examples
    --------
    >>> import numpy as np

    >>> vec1 = np.array(np.random.rand(1000))
    >>> vec2 = np.array(np.random.rand(1000))

    >>> args = (vec1, vec2)
    
    >>> timer(*args, operation=np.dot, n=1000000)
    8.942582607269287e-07
    """
    
    # Following list will hold the
    # time spent value for each iteration
    time_spent = []
    
    # Configuration info
    print("""
    -------------------------------------------
    
    ### {} Operation ###
    
    Arguments Info
    --------------
    args[0] Dimension: {},
    args[0] Shape: {},
    args[0] Length: {}
    """.format(operation.__name__,
        args[0].ndim,
        args[0].shape,
        len(args[0])))
    
    # If *args length is greater than 1, 
    # print out the info for second argument
    args_len = 0
    for i, arg in enumerate(args):
        args_len += 1
        
    if args_len > 1:
        print("""
    args[1] Dimension: {},
    args[1] Shape: {},
    args[1] Length: {}
        """.format(args[1].ndim,
            args[1].shape,
            len(args[1])))
   
    print("""
    Operation Info
    --------------
    Name: {},
    Docstring: {}
    
    Iterations Info
    ---------------
    # of iterations: {}""".format(
        operation.__name__,
        operation.__doc__[:100] + 
        "... For more info type 'operation?'",
        n))
    
    print("""
    -> Starting {} of iterations at: {}""".format(n, datetime.now()))
    
    if args_len > 1:
        for i in range(n):
            start = time.time()
            operation(args[0], args[1])
            time_spent.append(time.time()-start)
    else:
        for i in range(n):
            start = time.time()
            operation(args[0])
            time_spent.append(time.time()-start)
        
    avg_time_spent = np.sum(time_spent) / n
    std_time_spent = np.std(time_spent)
    
    print("""
    -> Average time spent: {} seconds,
    -> Std. deviation time spent: {} seconds
    
    -------------------------------------------
    """.format(avg_time_spent, std_time_spent))
    
    return avg_time_spent, std_time_spent

Docstring of timer function

In [249]:
print(timer.__doc__)


    Returns average time spent 
    for given operation and arguments.
    
    Parameters
    ----------
        *args: list (of numpy.ndarray, numpy.matrixlib.defmatrix.matrix or both)
            one or more numpy vectors or matrices
        operation: function
            numpy or scipy operation to be applied to given arguments
        n: int 
            number of iterations to apply given operation

    Returns
    -------
        avg_time_spent: double
            Average time spent to apply given operation
        std_time_spent: double
            Standard deviation of time spent to apply given operation
        
    Examples
    --------
    >>> import numpy as np

    >>> vec1 = np.array(np.random.rand(1000))
    >>> vec2 = np.array(np.random.rand(1000))

    >>> args = (vec1, vec2)
    
    >>> timer(*args, operation=np.dot, n=1000000)
    8.942582607269287e-07
    


### Vector - Vector Product

In [250]:
import numpy as np

vec1 = np.array(np.random.rand(1000))
vec2 = np.array(np.random.rand(1000))

In [271]:
args = [vec1, vec2]
timer(*args, operation=np.dot, n=1000000)


    -------------------------------------------
    
    ### dot Operation ###
    
    Arguments Info
    --------------
    args[0] Dimension: 1,
    args[0] Shape: (1000,),
    args[0] Length: 1000
    

    args[1] Dimension: 1,
    args[1] Shape: (1000,),
    args[1] Length: 1000
        

    Operation Info
    --------------
    Name: dot,
    Docstring: dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D... For more info type 'operation?'
    
    Iterations Info
    ---------------
    # of iterations: 1000000

    -> Starting 1000000 of iterations at: 2018-06-09 21:04:45.545944

    -> Average time spent: 1.0687923431396485e-06 seconds,
    -> Std. deviation time spent: 3.695899798414836e-06 seconds
    
    -------------------------------------------
    


(1.0687923431396485e-06, 3.695899798414836e-06)

### Vector - Matrix Product

In [148]:
mat1 = np.random.rand(1000,1000)

args = [vec1, mat1]

timer(*args, operation=np.dot, n=1000000)


    Arguments Info
    --------------
    args[0] Dimension: 1,
    args[0] Shape: (1000,),
    args[0] Length: 1000
    
    args[1] Dimension: 2,
    args[1] Shape: (1000, 1000),
    args[1] Length: 1000
    
    Operation Info
    --------------
    Name: dot,
    Docstring: dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D... For more info type 'operation?'
    
    Iterations Info
    ---------------
    # of iterations: 1000000

    -> Starting 1000000 of iterations: 2018-06-09 19:13:07.013949 at 

    -> Average time spent: 0.00020063393139839174 seconds,
    -> Std. deviation time spent: 9.579314466482879e-05 seconds
    


(0.00020063393139839174, 9.579314466482879e-05)

### Matrix - Matrix Product

In [272]:
mat1 = np.random.rand(100,100)
mat2 = np.random.rand(100,100)

args = [mat1, mat2]

timer(*args, operation=np.dot, n=1000000)


    -------------------------------------------
    
    ### dot Operation ###
    
    Arguments Info
    --------------
    args[0] Dimension: 2,
    args[0] Shape: (100, 100),
    args[0] Length: 100
    

    args[1] Dimension: 2,
    args[1] Shape: (100, 100),
    args[1] Length: 100
        

    Operation Info
    --------------
    Name: dot,
    Docstring: dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D... For more info type 'operation?'
    
    Iterations Info
    ---------------
    # of iterations: 1000000

    -> Starting 1000000 of iterations at: 2018-06-09 21:06:27.521641

    -> Average time spent: 7.155929303169251e-05 seconds,
    -> Std. deviation time spent: 1.8437869836742578e-05 seconds
    
    -------------------------------------------
    


(7.155929303169251e-05, 1.8437869836742578e-05)

### Benchmark Script: linalg_benchmark.py

In [275]:
args = [m1]
sv_dec = timer(*args, operation=np.linalg.svd, n=n)


    -------------------------------------------
    
    ### svd Operation ###
    
    Arguments Info
    --------------
    args[0] Dimension: 2,
    args[0] Shape: (10, 10),
    args[0] Length: 10
    

    Operation Info
    --------------
    Name: svd,
    Docstring: 
    Singular Value Decomposition.

    When `a` is a 2D array, it is factorized as ``u @ np.diag(s)... For more info type 'operation?'
    
    Iterations Info
    ---------------
    # of iterations: 10

    -> Starting 10 of iterations at: 2018-06-09 21:27:12.911005

    -> Average time spent: 0.00016016960144042968 seconds,
    -> Std. deviation time spent: 0.00014555827400804429 seconds
    
    -------------------------------------------
    


In [279]:
from __future__ import print_function

import time
from datetime import datetime


import numpy as np
from numpy.random import rand
from numpy.linalg import qr
from numpy.linalg import eig
from scipy.linalg import lu
from scipy.linalg import cholesky


# Seed for reproducibility
np.random.seed(8053)

dim = 100
n = 100

v1, v2 = np.array(rand(dim)), np.array(rand(dim))
m1, m2 = rand(dim, dim), rand(dim, dim)

# Vector - Vector Product
args = [v1, v2]
vv_product = timer(*args, operation=np.dot, n=n)

# Vector - Matrix Product
args = [v1, m1]
vm_product = timer(*args, operation=np.dot, n=n)

# Matrix - Matrix Product
args = [m1, m2]
mm_product = timer(*args, operation=np.dot, n=n)

# Singular-value Decomposition
args = [m1]
sv_dec = timer(*args, operation=np.linalg.svd, n=n)

# LU Decomposition
args = [m1]
lu_dec = timer(*args, operation=lu, n=n)

# QR Decomposition
args = [m1]
qr_dec = timer(*args, operation=qr, n=n)

# Cholesky Decomposition
M = np.array([[1, 3, 4], 
     [2, 13, 15], 
     [5, 31, 33]])
args = [M]
cholesky_dec = timer(*args, operation=cholesky, n=n)

# Eigenvalue Decomposition
args = [m1]
eig_dec = timer(*args, operation=eig, n=n)

print("""
V-V Product: {},
V-M Product: {},
M-M Product: {},
SV  Decomp.: {},
LU  Decomp.: {},
QR  Decomp.: {},
Cholesky D.: {},
Eigval Dec.: {}
""".format(vv_product,
           vm_product,
           mm_product,
           sv_dec,
           lu_dec,
           qr_dec,
           cholesky_dec,
           eig_dec))

print("""
NumPy Configuration:
--------------------
""")
np.__config__.show()


    -------------------------------------------
    
    ### dot Operation ###
    
    Arguments Info
    --------------
    args[0] Dimension: 1,
    args[0] Shape: (100,),
    args[0] Length: 100
    

    args[1] Dimension: 1,
    args[1] Shape: (100,),
    args[1] Length: 100
        

    Operation Info
    --------------
    Name: dot,
    Docstring: dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D... For more info type 'operation?'
    
    Iterations Info
    ---------------
    # of iterations: 100

    -> Starting 100 of iterations at: 2018-06-09 21:30:10.204886

    -> Average time spent: 3.025531768798828e-06 seconds,
    -> Std. deviation time spent: 4.170580226605431e-06 seconds
    
    -------------------------------------------
    

    -------------------------------------------
    
    ### dot Operation ###
    
    Arguments Info
    --------------
    args[0] Dimension: 1,
    args[0] Shape: (100,),
    args[0


NumPy Configuration:
--------------------

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


### Singular-value Decomposition

In [61]:
import numpy as np

M = np.random.randint(low=0, high=20, size=20).reshape(4,5)

In [62]:
print(M)

[[18 15 11 13 19]
 [ 1  6  8 13 18]
 [ 9  7 15 13 10]
 [17 15 12 14 12]]


In [63]:
U, d, VT = np.linalg.svd(M)

In [64]:
print("U:\n {}\n".format(U))
print("d:\n {}\n".format(d))
print("VT:\n {}".format(VT))

U:
 [[-0.60773852 -0.22318957  0.5276743  -0.54990921]
 [-0.38123886  0.86738201  0.19333528  0.25480749]
 [-0.42657252  0.10181457 -0.82343563 -0.36003255]
 [-0.55076919 -0.43297652 -0.07832665  0.70925987]]

d:
 [56.31276456 13.15721839  8.08763849  2.51997135]

VT:
 [[-0.43547429 -0.40223663 -0.40386674 -0.46371223 -0.52002929]
 [-0.72920427 -0.29835313  0.06197899  0.27638212  0.54682545]
 [ 0.11733943  0.26412864 -0.73449806 -0.30022507  0.53557916]
 [-0.32795351  0.55511623 -0.3571117   0.56067806 -0.3773643 ]
 [-0.39661218  0.60932187  0.40747282 -0.55144258  0.03609177]]


In [65]:
# Setting full_matrices to false gives you reduced form where small values close to zero are excluded
U, d, VT = np.linalg.svd(M, full_matrices=False)

print("U:\n {}\n".format(U))
print("d:\n {}\n".format(d))
print("VT:\n {}".format(VT))

U:
 [[-0.60773852 -0.22318957  0.5276743  -0.54990921]
 [-0.38123886  0.86738201  0.19333528  0.25480749]
 [-0.42657252  0.10181457 -0.82343563 -0.36003255]
 [-0.55076919 -0.43297652 -0.07832665  0.70925987]]

d:
 [56.31276456 13.15721839  8.08763849  2.51997135]

VT:
 [[-0.43547429 -0.40223663 -0.40386674 -0.46371223 -0.52002929]
 [-0.72920427 -0.29835313  0.06197899  0.27638212  0.54682545]
 [ 0.11733943  0.26412864 -0.73449806 -0.30022507  0.53557916]
 [-0.32795351  0.55511623 -0.3571117   0.56067806 -0.3773643 ]]


## LU decomposition

In [66]:
from numpy import array
from scipy.linalg import lu

M = np.random.randint(low=0, high=20, size=25).reshape(5,5)
print(M)

[[18 12 14 15  2]
 [ 4  2 12 18  3]
 [ 9 19  5 16  8]
 [15 19  6 16 11]
 [ 1 19  2 18 17]]


In [67]:
P, L, U = lu(M)

print("P:\n {}\n".format(P))
print("L:\n {}\n".format(L))
print("U:\n {}".format(U))

P:
 [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]

L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.05555556  1.          0.          0.          0.        ]
 [ 0.22222222 -0.03636364  1.          0.          0.        ]
 [ 0.83333333  0.49090909 -0.70149254  1.          0.        ]
 [ 0.5         0.70909091 -0.32089552  0.21279832  1.        ]]

U:
 [[18.         12.         14.         15.          2.        ]
 [ 0.         18.33333333  1.22222222 17.16666667 16.88888889]
 [ 0.          0.          8.93333333 15.29090909  3.16969697]
 [ 0.          0.          0.          5.79918589  3.26594301]
 [ 0.          0.          0.          0.         -4.65360318]]


In [68]:
P.dot(L).dot(U)

array([[18., 12., 14., 15.,  2.],
       [ 4.,  2., 12., 18.,  3.],
       [ 9., 19.,  5., 16.,  8.],
       [15., 19.,  6., 16., 11.],
       [ 1., 19.,  2., 18., 17.]])

## QR decomposition

In [172]:
from numpy.linalg import qr

In [69]:
from numpy import array
from numpy.linalg import qr

M = np.random.randint(low=0, high=20, size=20).reshape(4,5)
print(M)

[[14  6  0 19  3]
 [ 9  6 17  8  8]
 [ 4 13 17  4  4]
 [ 0  0  2  7 11]]


In [70]:
Q, R = qr(M, 'complete')

print("Q:\n {}\n".format(Q))
print("R:\n {}".format(R))

Q:
 [[-0.81788873  0.28364908 -0.49345895  0.08425845]
 [-0.52578561 -0.01509441  0.83834961 -0.14314877]
 [-0.2336825  -0.95880935 -0.15918031  0.02718015]
 [-0.         -0.          0.16831464  0.98573332]]

R:
 [[-17.11724277 -11.09991852 -12.91095786 -20.68090082  -7.59468109]
 [  0.         -10.85319349 -16.5563638    1.43333978  -3.10504542]
 [  0.           0.          11.88250752  -2.12744187   6.4411599 ]
 [  0.           0.           0.           7.4645743   10.05937231]]


In [71]:
Q.dot(R)

array([[1.40000000e+01, 6.00000000e+00, 1.77635684e-15, 1.90000000e+01,
        3.00000000e+00],
       [9.00000000e+00, 6.00000000e+00, 1.70000000e+01, 8.00000000e+00,
        8.00000000e+00],
       [4.00000000e+00, 1.30000000e+01, 1.70000000e+01, 4.00000000e+00,
        4.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 7.00000000e+00,
        1.10000000e+01]])

## Cholesky decomposition

In [202]:
from numpy import array
from scipy.linalg import cholesky

M = np.array([[1, 3, 4], 
     [2, 13, 15], 
     [5, 31, 33]])
print(M)

[[ 1  3  4]
 [ 2 13 15]
 [ 5 31 33]]


In [203]:
L = cholesky(M)
print(L)

[[1.         3.         4.        ]
 [0.         2.         1.5       ]
 [0.         0.         3.84057287]]


In [204]:
L.T.dot(L)

array([[ 1.,  3.,  4.],
       [ 3., 13., 15.],
       [ 4., 15., 33.]])

## Eigenvalue decomposition

In [72]:
from numpy import array
from numpy.linalg import eig

M = np.random.randint(low=0, high=20, size=25).reshape(5,5)
print(M)

[[13  9  5  0 12]
 [13  6 11  8 15]
 [16 17 15 12  1]
 [17  8  5  7  5]
 [10  6 18  5 19]]


In [76]:
V, Q = eig(M)

print("Eigenvalues:\n {}\n".format(V))
print("Eigenvectors:\n {}".format(Q))

Eigenvalues:
 [50.79415691 +0.j          5.76076687+11.52079216j
  5.76076687-11.52079216j -1.15784533 +3.28961651j
 -1.15784533 -3.28961651j]

Eigenvectors:
 [[ 0.34875973+0.j         -0.36831427+0.21725348j -0.36831427-0.21725348j
  -0.40737336-0.19752276j -0.40737336+0.19752276j]
 [ 0.46629571+0.j         -0.08027011-0.03330739j -0.08027011+0.03330739j
   0.58904402+0.j          0.58904402-0.j        ]
 [ 0.50628483+0.j          0.62334823+0.j          0.62334823-0.j
  -0.27738359-0.22063552j -0.27738359+0.22063552j]
 [ 0.33975886+0.j          0.14035596+0.39427693j  0.14035596-0.39427693j
   0.125282  +0.46663129j  0.125282  -0.46663129j]
 [ 0.53774952+0.j         -0.18591079-0.45968785j -0.18591079+0.45968785j
   0.20856874+0.21329768j  0.20856874-0.21329768j]]


In [77]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv

Q.dot(diag(V)).dot(inv(Q))

array([[1.30000000e+01-2.88657986e-15j, 9.00000000e+00-2.33146835e-15j,
        5.00000000e+00+2.38697950e-15j, 1.17683641e-14+1.77635684e-15j,
        1.20000000e+01-4.99600361e-16j],
       [1.30000000e+01-4.32986980e-15j, 6.00000000e+00-3.99680289e-15j,
        1.10000000e+01+3.38618023e-15j, 8.00000000e+00+1.72084569e-15j,
        1.50000000e+01-2.77555756e-16j],
       [1.60000000e+01-7.21644966e-15j, 1.70000000e+01-6.66133815e-15j,
        1.50000000e+01+5.71764858e-15j, 1.20000000e+01+2.99760217e-15j,
        1.00000000e+00-6.66133815e-16j],
       [1.70000000e+01-5.27355937e-15j, 8.00000000e+00-3.10862447e-15j,
        5.00000000e+00+4.27435864e-15j, 7.00000000e+00+2.22044605e-15j,
        5.00000000e+00-1.22124533e-15j],
       [1.00000000e+01-3.60822483e-15j, 6.00000000e+00-4.21884749e-15j,
        1.80000000e+01+2.27595720e-15j, 5.00000000e+00+1.55431223e-15j,
        1.90000000e+01+3.88578059e-16j]])